### ISSUE TITLE
thanks man!

### ISSUE THREAD

**Issue by ghost** [pepzwee/mediafire-getlink#1]
Hi Kristjan.
Thanks a lot for the fixed version of my module.
Can I put your code to update my module? (Don't worry, I will credit you).
Thank you!
[and if you ask, here is the repo: https://github.com/azgar44/mediafire-link.git].

**Comment by pepzwee** [comment]
Hey!

Yeah, you can use this repo code to update your module - that's totally ok with me. :)

By the way the code updates I've made require Node version >= 14.
